[package]
name = "ic-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ic-core = { path = "../ic-core" }
ic-store = { path = "../ic-store" }
serde_json.workspace = true
thiserror.workspace = true
ureq.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
