import InquiryCalculus.Meta.Ambient
import InquiryCalculus.Legacy.V20.Binding
import InquiryCalculus.Legacy.V20.Types
import InquiryCalculus.Legacy.V20.Forms
import InquiryCalculus.Legacy.V20.Relations
import InquiryCalculus.Legacy.V20.Refinement
import InquiryCalculus.Legacy.V20.FormulaGrammar
import InquiryCalculus.Legacy.V20.MinimalLogicalBasis
import InquiryCalculus.Legacy.V20.RelationExpressionIR
import InquiryCalculus.Legacy.V20.RelationSchemaPorts
import InquiryCalculus.Legacy.V20.PartialBindingFiber
import InquiryCalculus.Legacy.V20.CanonicalQuestionSyntax
import InquiryCalculus.Legacy.V20.AnswerCarrierValidity
import InquiryCalculus.Legacy.V20.PropositionNotWarrant
import InquiryCalculus.Legacy.V20.ManyQuestionsGeneration
import InquiryCalculus.Legacy.V20.DischargeModeSyntax
import InquiryCalculus.Legacy.V20.QuestionCompositionSyntax
import InquiryCalculus.Legacy.V20.QuestionConditionedDiscrimination
import InquiryCalculus.Legacy.V20.QuestionRefinementPreorder
import InquiryCalculus.Legacy.V20.QuestionRefinementSemantics
import InquiryCalculus.Legacy.V20.QuestionJointActiveRefinement
import InquiryCalculus.Legacy.V20.QuestionRedundancy
import InquiryCalculus.Legacy.V20.PrecisionNotImprovement
import InquiryCalculus.Legacy.V20.RelationalSections
import InquiryCalculus.Legacy.V20.SolutionFibers
import InquiryCalculus.Legacy.V20.QuestionStructuredHole
import InquiryCalculus.Legacy.V20.RelationalAbstraction
import InquiryCalculus.Legacy.V20.AbstractionByRemoval
import InquiryCalculus.Legacy.V20.SolutionFieldWeb
import InquiryCalculus.Legacy.V20.IndexedMeetRefinement
import InquiryCalculus.Legacy.V20.PropertyImageHole
import InquiryCalculus.Legacy.V20.ProtectedDetermination
import InquiryCalculus.Legacy.V20.ExactDeterminationSignature
import InquiryCalculus.Legacy.V20.ResidualAmbiguity
import InquiryCalculus.Legacy.V20.RepresentationDefect
import InquiryCalculus.Legacy.V20.SeparatingContextQuestion
import InquiryCalculus.Legacy.V20.RepresentationQuestion
import InquiryCalculus.Legacy.V20.GrainQuestion
import InquiryCalculus.Legacy.V20.ProbeToolInventionQuestion
import InquiryCalculus.Legacy.V20.RepresentationGapLocalization
import InquiryCalculus.Legacy.V20.TypedDistinctionSchema
import InquiryCalculus.Legacy.V20.CandidateBoundaryIncidence
import InquiryCalculus.Legacy.V20.BoundaryPointProfile
import InquiryCalculus.Legacy.V20.BoundaryPointRegeneration
import InquiryCalculus.Legacy.V20.DeterminationPresentation
import InquiryCalculus.Legacy.V20.PositiveDepartureWitness
import InquiryCalculus.Legacy.V20.DepartureRelativePositivity
import InquiryCalculus.Legacy.V20.DerivedBoundaryCrossing
import InquiryCalculus.Legacy.V20.RelationAndNegationUse
import InquiryCalculus.Legacy.V20.PositiveNegationFilling
import InquiryCalculus.Legacy.V20.SemanticAndExecutionCoverage
import InquiryCalculus.Legacy.V20.TaggedNegationFrontier
import InquiryCalculus.Legacy.V20.UseSpecificReturnFiber
import InquiryCalculus.Legacy.V20.ProtectedRecovery
import InquiryCalculus.Legacy.V20.SourceWebRecoveryProfile
import InquiryCalculus.Legacy.V20.ThreeValuedRecoveryLossProfile
import InquiryCalculus.Legacy.V20.RegenerativeEconomyFrontier
import InquiryCalculus.Legacy.V20.RequiredDischarge
import InquiryCalculus.Legacy.V20.ResolutionCarriers
import InquiryCalculus.Legacy.V20.ResolutionOutcome
import InquiryCalculus.Legacy.V20.InquirySourceGrammar
import InquiryCalculus.Legacy.V20.ResidualQuestionGenerator
import InquiryCalculus.Legacy.V20.CheckedAskOccurrence
import InquiryCalculus.Legacy.V20.HeadQuestion
import InquiryCalculus.Legacy.V20.OccurrenceIndexedQuestionSuccession
import InquiryCalculus.Legacy.V20.QuestionSuccessionTypingClaim
import InquiryCalculus.Legacy.V20.DependentReciprocalProgram
import InquiryCalculus.Legacy.V20.HoleSolving
import InquiryCalculus.Legacy.V20.RepresentationSearch
import InquiryCalculus.Legacy.V20.ProgramCoreGrammar
import InquiryCalculus.Legacy.V20.SourceSafeAskLowering
import InquiryCalculus.Legacy.V20.SourceAskCompilationSafetyClaim
import InquiryCalculus.Legacy.V20.SequencingComposition

/-!
# Inquiry Calculus formal successor

This library is the machine-checked candidate successor. Its current import surface is deliberately
limited to the checked ambient boundary and the source-bound v2.0 binding/type syntax; later
modules enter only through a live frontier and checked dependency propagation.
-/
