#!/usr/bin/env node
"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process"),crypto=require("node:crypto");
const root=path.resolve(__dirname,".."),moduleName="InquiryCalculus.Legacy.V20.RegenerativeEconomyCorrespondence",modulePath="formal/InquiryCalculus/Legacy/V20/RegenerativeEconomyCorrespondence.lean",texDigest="1f548e0fa3e8374a01b6268e813cedcc757b26ed460adb5b82fe8ba60ca1dd89",hash=x=>crypto.createHash("sha256").update(x).digest("hex");
function source(tex,classification){assert.equal(hash(tex),texDigest);const r=classification.records.filter(x=>x.source_id==="PRED-TEX-DECL-DEF-REGENERATIVE-ECONOMY");assert.equal(r.length,1);const x=r[0],lines=tex.toString().replace(/\r\n?/gu,"\n").split("\n"),excerpt=lines.slice(4183,4207).map(s=>s.trimEnd()).join("\n").trim();assert.equal(x.source.start_line,4184);assert.equal(x.source.end_line,4207);assert.equal(x.disposition,"FormalDefinition");assert.equal(x.source.revision,`sha256:${texDigest}`);assert.equal(x.source.sha256,hash(excerpt));assert.equal(x.source_excerpt_sha256,hash(excerpt));return x;}
const open=`open InquiryCalculus.Legacy.V20 InquiryCalculus.Legacy.V20.RegenerativeEconomyCorrespondence\n`;
const finite=`
open Countermodel RegenerativeSufficiency.Countermodel
example (s : Source2) : namedConsequenceFactors s s ∧ ¬ DependentLicensedCandidate protectedComponents completeReconstruction missingRevision completeLicense s s := factorOnlyNotLicensedCandidate s
example : regenerativeEconomyFrontier equalityPreorder.le everyBoolCandidate false := falseIsEconomical
example : regenerativeEconomyFrontier equalityPreorder.le everyBoolCandidate true := trueIsEconomical
example : false ≠ true := economicalFrontierNotUnique
example : ¬ ∀ left right, equalityPreorder.le left right ∨ equalityPreorder.le right left := equalityPreorderNotTotal
example : ∀ r, ¬ regenerativeEconomyFrontier equalityPreorder.le emptyCandidate r := emptyAdmittedRegion
`;
const audits=["frontierMemberInquiryRegenerative","frontierMemberLicensed","noCandidateNoFrontier","Countermodel.factorOnlyNotLicensedCandidate","Countermodel.falseIsEconomical","Countermodel.trueIsEconomical","Countermodel.economicalFrontierNotUnique","Countermodel.equalityPreorderNotTotal","Countermodel.emptyAdmittedRegion"];
function finiteModel(){const masks=[0,1,2,3],frontier=(candidate,le,x)=>candidate(x)&&masks.every(y=>!candidate(y)||!le(y,x)||le(x,y));const eq=(a,b)=>a===b,all=()=>true,none=()=>false;assert.deepEqual(masks.filter(x=>frontier(all,eq,x)),masks);assert.deepEqual(masks.filter(x=>frontier(none,eq,x)),[]);assert.equal(true&&false,false);}
function main(){assert.ok(process.argv.slice(2).every(x=>x==="--compile"));const read=p=>fs.readFileSync(path.join(root,p)),tex=read("Inquiry_Calculus_v2_0.tex"),c=JSON.parse(read("formal-successor/PREDECESSOR_TEX_CLASSIFICATION.json")),record=source(tex,c),doc=read("formal-successor/PHASE_B_REGENERATIVE_ECONOMY_CORRESPONDENCE.md").toString(),lean=read(modulePath).toString();assert.match(doc,/PRED-TEX-DECL-DEF-REGENERATIVE-ECONOMY \| 4184–4207 \| FormalDefinition/u);for(const mutate of [x=>x.records=x.records.filter(r=>r.source_id!==record.source_id),x=>x.records.find(r=>r.source_id===record.source_id).disposition="FormalTheorem",x=>x.records.find(r=>r.source_id===record.source_id).source.start_line--]){const d=structuredClone(c);mutate(d);assert.throws(()=>source(tex,d));}assert.throws(()=>source(Buffer.concat([tex,Buffer.from("\n")]),c));finiteModel();assert.doesNotMatch(lean,/\b(?:sorry|admit|axiom|unsafe|native_decide|Classical\.choose)\b/u);assert.match(read("formal/InquiryCalculus.lean").toString(),/^import InquiryCalculus\.Legacy\.V20\.RegenerativeEconomyCorrespondence\r?$/mu);console.log(`PASS source and finite economy checks; module sha256 ${hash(lean)}`);if(!process.argv.includes("--compile"))return;const dir=fs.mkdtempSync(path.join(os.tmpdir(),"ic-economy-")),run=a=>cp.spawnSync("lake",a,{cwd:path.join(root,"formal"),encoding:"utf8",windowsHide:true}),probe=(n,b,reject=false,own=false)=>{const f=path.join(dir,n+".lean");fs.writeFileSync(f,(own?"":`import ${moduleName}\n${open}`)+b);const r=run(["env","lean",f]),o=r.stdout+r.stderr;if(reject){assert.notEqual(r.status,0,`accepted ${n}`);assert.match(o,/error:/u)}else assert.equal(r.status,0,o);return o};assert.equal(run(["build",moduleName,"--wfail"]).status,0);let out=probe("contracts",finite+audits.map(n=>`\n#print axioms ${moduleName}.${n}`).join(""));for(const n of audits)assert.match(out,new RegExp(`'${moduleName.replaceAll(".","\\.")}\\.${n.replaceAll(".","\\.")}' does not depend on any axioms`));for(const [n,b] of [["factor-is-not-candidate",finite+`example (s : Source2) : DependentLicensedCandidate protectedComponents completeReconstruction missingRevision completeLicense s s := (factorOnlyNotLicensedCandidate s).1`],["not-unique",finite+`example : false = true := rfl`],["not-nonempty",finite+`example : ∃ r, regenerativeEconomyFrontier equalityPreorder.le emptyCandidate r := ⟨false, falseIsEconomical⟩`]])probe(n,b,true);for(const [n,m] of [["drop-license",s=>s.replace("∧\n      LicenseSatisfied","∨\n      LicenseSatisfied")],["force-total",s=>s.replace("transitive :", "total : ∀ left right, le left right ∨ le right left\n  transitive :")]]){const changed=m(lean);assert.notEqual(changed,lean);probe(n,changed+"\n"+open+finite,true,true)}console.log(`PASS dependent economy correspondence; 3 rejected counterclaims; 2 rejected ablations; ${audits.length} axiom-free audits`)}
try{main()}catch(e){console.error(e.message);process.exitCode=1}
